version: '3.8'

services:
  cyberparkit-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cyberparkit-web
    restart: unless-stopped
    ports:
      - "80:80"
    # If you need environment variables
    # environment:
    #   - NODE_ENV=production
    networks:
      - app-network

  # Optional: Add a reverse proxy like Traefik for SSL
  # traefik:
  #   image: traefik:v2.5
  #   container_name: traefik
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./traefik:/etc/traefik
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge 